.travis.yml
packages/react-scripts/CHANGELOG.md
packages/react-scripts/package.json
packages/react-scripts/scripts/init.js
packages/react-scripts/template/src/App.jsx
packages/react-scripts/template/src/App.scss

- Removed BpkParagraph and BpkHeading
- Added BpkText
- Updated other Backpack dependencies

Replace BpkParagraph and BpkHeading with BpkText in template

---

packages/react-scripts/CHANGELOG.md
packages/react-scripts/config/webpack.config.prod.js
packages/react-scripts/config/webpack.config.ssr.js
packages/react-scripts/package.json

For prod and SSR builds include `optimize-css-assets-webpack-plugin` to
optimize duplication in CSS output.

[BPK-838] Add `optimize-css-assets-webpack-plugin`

---

packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js

I think I may be missing something, is this all that's required? I read through the Slack thread mentioned in BPK-850 and this was all I could ascertain from it. Sorry for the delay, I've been reading a lot of Webpack 2 docs.

[BPK-850] Use contenthash instead of hash in css-modules

---

packages/react-scripts/README.md

I've provided explicit instructions for releasing `backpack-react-scripts` only as the instructions in the upstream CONTRIBUTING.md were not applicable or useful.
I also moved the "Keeping our fork updated" section to the bottom.

[NOJIRA] Improve release instructions

---

packages/react-scripts/CHANGELOG.md
packages/react-scripts/config/paths.js
packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js
packages/react-scripts/config/webpack.config.ssr.js

@matthewdavidson 
This is adding the `saddlebag-` prefix to be auto compiled by backpack-react-scripts since we're going to be publishing uncompiled versions of saddlebag.
cc @danrr

adding saddlebag module regex to be compiled

---

packages/react-scripts/CHANGELOG.md
packages/react-scripts/scripts/utils/createJestConfig.js

@matthewdavidson 
Adding `saddlebag-` prefix to be compiled by `jest` for testing

adding saddlebag prefix to jest config

---

packages/react-scripts/CHANGELOG.md
packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js
packages/react-scripts/package.json
tasks/e2e-simple.sh

See https://webpack.js.org/configuration/output/#output-jsonpfunction.
Also added lodash as a direct dependency. this will not affect install times as lodash was already a transient dependency:
```
├─┬ babel-core@6.26.0
│ ├─┬ babel-generator@6.26.1
│ │ └── lodash@4.17.5  deduped
│ ├─┬ babel-register@6.26.0
│ │ └── lodash@4.17.5  deduped
│ ├─┬ babel-template@6.26.0
│ │ └── lodash@4.17.5  deduped
│ ├─┬ babel-traverse@6.26.0
│ │ └── lodash@4.17.5  deduped
│ ├─┬ babel-types@6.26.0
│ │ └── lodash@4.17.5  deduped
│ └── lodash@4.17.5  deduped
├─┬ babel-eslint@8.2.2
│ ├─┬ @babel/traverse@7.0.0-beta.40
│ │ ├─┬ @babel/generator@7.0.0-beta.40
│ │ │ └── lodash@4.17.5  deduped
│ │ ├─┬ @babel/helper-function-name@7.0.0-beta.40
│ │ │ └─┬ @babel/template@7.0.0-beta.40
│ │ │   └── lodash@4.17.5  deduped
│ …
```

[NOJIRA] - Use package.json name for jsonp function

---

packages/react-scripts/CHANGELOG.md
packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js
packages/react-scripts/config/webpack.config.ssr.js
packages/react-scripts/template/README.md

Adds new `amdExcludes` option for consumers:
```json
"backpack-react-scripts": {
"amdExcludes": [
"globalize"
]
}
```
`lodash` is still excluded by default.

[BPK-1321] Add option to disable AMD parsing for specific modules

---

packages/react-scripts/config/webpack.config.js
packages/react-scripts/config/webpack.config.ssr.js
packages/react-scripts/package.json

Add support for server rendered async components into backpack-react-scripts. This allows any users of backpack-react-scripts to easily add code splitting by route to their projects so that their users only download the necessary JS for the page they are currently on.
In order to use async components and have them server side rendered, you will need to add the following code to any project. More detailed documentation can be found here https://www.smooth-code.com/open-source/loadable-components/docs/server-side-rendering/
1. Install `@loadable/component` and `@loadable/server` in the client package these both must be in client package and not in the server package as loadable/component and and loadable/server use a shared React Context to communicate.
2. Make your component async by …

Add Support for loadable/component

---

packages/react-scripts/CHANGELOG.md
packages/react-scripts/README.md
packages/react-scripts/config/webpack.config.js
packages/react-scripts/package.json

Add the ability to configure the contents of `vendors` chunk in when `enableAutomaticChunking` is enabled.
You can now use `vendorsChunkRegex` to customise the behaviour which would otherwise be `/[\\/]node_modules[\\/]/`

Add `vendorsChunkRegex`

---

packages/react-scripts/README.md

This PR fixes the instructions on how to use BRS to specify the current supported BRS version.
Before when we were just specifying `npx create-react-app my-app --scripts-version=backpack-react-scripts` unless you had a specific CRA version installed locally it would pull the latest CRA from npm.
In the latest version there was templating added which BRS not yet supports so when running the regular script without specifying a version it would grab the latest. 3.3.0 and error due to this new feature, which would just output a folder with node_modules and a package.json which is not the expected output.

[NO JIRA]: Fixed usage script

---

packages/react-scripts/migrating-from-v6-to-v7.md

Update to reflect newest versions of Skyscanner linting configurations, prompted by the deprecation of `eslint-config-skyscanner-with-prettier` and removal of peer dependencies in v5 of `eslint-config-skyscanner` and v2 of `stylelint-config-skyscanner`.

Update v6 - v7 migration guide

---

packages/react-scripts/README.md
packages/react-scripts/config/webpack.config.js

This makes #79 - Enabled SRI an opt in functionality where a user will set `sriEnabled` in the BRS config.
Doing this overrides any value set by `crossOriginLoading` when this is enabled

[BPK-3997]: Make SRI optional

---

packages/react-scripts/README.md

Currently the latest version available is `4.0.1`
By running `npx create-react-app@4.0.0 my-app --scripts-version=@skyscanner/backpack-react-scripts --template @skyscanner/backpack --use-npm` the output would be:
```
npx: installed 92 in 8.388s
You are running `create-react-app` 4.0.0, which is behind the latest release (4.0.1).
We no longer support global installation of Create React App.
Please remove any global installs with one of the following commands:
- npm uninstall -g create-react-app
- yarn global remove create-react-app
The latest instructions for creating a new app can be found here:
https://create-react-app.dev/docs/getting-started/
```
Using `npx create-react-app@4.0.1 ...` fixes it 😉

Update create-react-app@4.0.1 README.md

---

packages/react-scripts/config/webpack.config.ssr.js
packages/react-scripts/package.json
packages/react-scripts/scripts/start-ssr.js
packages/react-scripts/scripts/utils/MultiCompilerUi.js
packages/react-scripts/scripts/utils/customWebpackUtils.js
packages/react-scripts/scripts/utils/forkSsr.js

This PR supersedes #96.
The current `v9-alpha` with Loadable SSR support adds a `start-ssr` script to run the SSR build during development, which means having to run `react-scripts start` and `react-scripts start-ssr` in parallel. This doesn't play well with how Docker is set up in MShell microsites - the `client` container can only run one process.
Vulcan have run a spike to look in to options to improve this and agreed the approach here with @olliecurtis, which is to update the `start-ssr` script to run both the `web` and `ssr` builds in dev mode:
- A `WebpackDevServer` runs watches the `web` build on serves files on `localhost:3000`, exactly as `start` does
- A second Webpack compiler watches the `ssr` build and writes to the filesystem
The `start-ssr` script is now a clone of `start` …

[VUL-813] Update start-ssr script to run web & ssr builds

---

packages/react-scripts/CHANGELOG.md
packages/react-scripts/config/paths.js
packages/react-scripts/config/webpack.config.js
packages/react-scripts/config/webpack.config.ssr.js

From [LEOP-69](https://gojira.skyscanner.net/browse/LEOP-69), we can get the benefit from `cache-loader` on CI.
More detail Here: [cache-loader on GitHub Actions](https://github.com/Skyscanner/test-banana/actions/runs/1014476314)
- Apply `cache-loader` on CI
- Put `cache-loader` before `sass-loader` since `sass-loader` is the most expensive
- Add `SHOULD_USE_CACHE_LOADER` to control if use `cache-loader` or not since not all the web projects at Skyscanner have applied the cache strategy

[LEOP-55]: Apply cache-loader on CI

---

packages/react-scripts/CHANGELOG.md
packages/react-scripts/config/webpack.config.js
packages/react-scripts/config/webpack.config.ssr.js

- Leopard has finally gotten the conclusion that we should use `cache-loader` with `git-restore-mtime`
- `cache-loader-hash` && `ci-cache-loader` are both not quite active and popular, we should still use `cache-loader`
- `cache-loader` above `resolve-url-loader` will generate small size of cache files, and it is faster to upload and download from `AWS S3`, it is also faster to read the cache files, so it can give us the best performance for speeding up build process.
- [Experiments To Use cache-loader](https://confluence.skyscannertools.net/display/LEOP/Experiments+To+Use+cache-loader)
- [Data From Using cache-loader-hash && ci-cache-loader](https://confluence.skyscannertools.net/pages/viewpage.action?pageId=541794241)
- [Comparison Of cache-loader && cache-loader-hash && …

[LEOP-166]: Move cache-loader above resolve-url-loader to get the best performance

---

packages/react-scripts/CHANGELOG.md
packages/react-scripts/package-lock.json
packages/react-scripts/package.json

`react-scripts` comes with several linting dependencies preinstalled, both directly in its package.json and via it installing `eslint-config-react-app`.
https://github.com/facebook/create-react-app/blob/main/packages/react-scripts/package.json#L46-L48
In our fork we uninstalled `eslint`, `eslint-config-react-app`, `eslint-webpack-plugin`.
We provide linting via [`eslint-config-skyscanner`](https://github.com/Skyscanner/eslint-config-skyscanner), but do not install this directly in `backpack-react-scripts` and allow consumers to optionally choose to install it or not.
In https://github.com/Skyscanner/eslint-config-skyscanner/pull/214 we add the TypeScript ESLint packages to `eslint-config-skyscanner`.
Following our own pattern this means they are no longer required in …

Uninstall typescript linting dependencies from react-scripts

---

.github/workflows/build-brs.yml
.github/workflows/build.yml
.github/workflows/lint.yml
tasks/e2e-installs.sh

- The ubuntu-latest runner has upgraded the node version to v16 as default
- `create-react-app` command requires Node.js v14 or v16, if not, it will faill on running
- `node-sass` v4 and a low version of `node-gyp` just support Node.js v12 and v14 but not support v16
- Set all Node.js versions to v14 to make all workflows pass the checking on CI

[NO JIRA]: Set node version to v14.x in workflow

---

packages/react-scripts/config/webpack.config.js
packages/react-scripts/config/webpack.config.ssr.js
packages/react-scripts/package.json

For sass-loader 8.0.0 and higher, the default number of threads used is 4, and thread size can be configured by setting the UV_THREADPOOL_SIZE env var, it can improve the build performance.
Detail: https://confluence.skyscannertools.net/display/LEOP/Standardizing+backpack-react-scripts%28BRS%29+As+The+Only+Build+Tool

[LEOP-280]Upgrade sass-loader to v10.x

---

packages/react-scripts/backpack-addons/README.md
packages/react-scripts/backpack-addons/babelIncludePrefixes.js
packages/react-scripts/config/webpack.config.js
packages/react-scripts/config/webpack.config.ssr.js

[LEOP-316](https://gojira.skyscanner.net/browse/LEOP-316)
- Extracting babelIncludePrefixes feature to separate file
- Using `require(.../backpack-addons/...)` instead of writing it inline.
- Add README.md to describe the feature

[LEOP-316]Extract babelIncludePrefixes feature

---

packages/react-scripts/backpack-addons/README.md
packages/react-scripts/backpack-addons/crossOriginLoading.js
packages/react-scripts/backpack-addons/sriEnabled.js
packages/react-scripts/config/webpack.config.js

[LEOP-316](https://gojira.skyscanner.net/browse/LEOP-316)
- Extracting crossOriginLoading and sriEnabled features to separate file
- Use require(.../backpack-addons/...) instead of writing it inline
- Add README.md to describe the feature

[LEOP-316]Extract crossOriginLoading and sriEnabled features

---

packages/react-scripts/backpack-addons/README.md
packages/react-scripts/backpack-addons/ignoreCssWarnings.js
packages/react-scripts/config/webpack.config.js

[LEOP-316](https://gojira.skyscanner.net/browse/LEOP-316)
- Extracting ignoreCssWarnings feature to separate file
- Use `require(.../backpack-addons/...)` instead of writing it inline
- Add README.md to describe the feature

[LEOP-316]Extract ignoreCssWarnings feature

---

packages/react-scripts/backpack-addons/amdExcludes.js
packages/react-scripts/config/webpack.config.js
packages/react-scripts/config/webpack.config.ssr.js

Test disable AMD parsing when filename contains `lodash` or `amdExcludes`
step:
- extract amdExcludes to backpack-addons
- test for banana

[LEOP-317]Extract amdExcludes

---

packages/react-scripts/backpack-addons/splitChunks.js
packages/react-scripts/config/webpack.config.js

Splitchunks can separate common code from chunks, and splitchunks can split modules according to `cacheGroups`. Webpack has two groups, vendors and Default, by default, and you can also add groups by redefining the properties in both groups.
step:
- extract splitChunks to backpack-addons
- test for banana

[LEOP-317]Extract splitChunks

---

packages/react-scripts/backpack-addons/externals.js
packages/react-scripts/config/webpack.config.js
packages/react-scripts/config/webpack.config.ssr.js

externals: Prevent bundling of certain imported packages and instead retrieve these external dependencies at runtime.
For example, to include jQuery from a CDN instead of bundling it.
step:
- extract externals to backpack-addons
- test for banana

[LEOP-317]Extract externals

---

packages/react-scripts/backpack-addons/splitChunks.js

Resolve about banana build error(The **vendor.xxx.js** file is generated): 
And Github Action fail:
https://github.skyscannertools.net/dingo/banana/actions/runs/2953
Edit:
- delete splitChunks vender name

[No JIRA]Delete splitChunks vendor name

---

packages/react-scripts/backpack-addons/splitChunks.js
packages/react-scripts/backpack-addons/sriEnabled.js

Splitchunks: in webpack5, optimization.splitChunks name: true removed: Automatic names are no longer supported, see [here](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#changes-to-the-structure).
sriEnabled: migrate v1 to v5 use new import syntax, see [here](https://github.com/waysact/webpack-subresource-integrity/blob/next/MIGRATE-v1-to-v5.md#migrate-from-version-1x-to-version-5x).
change files:
- splitChunks: remove `name` when development is ture
- sirEnabled: change `const SubresourceIntegrityPlugin = require("webpack-subresource-integrity");` to `const { SubresourceIntegrityPlugin } = require("webpack-subresource-integrity")`

[No JIRA]SplitChunks remove name and SubresourceIntegrityPlugin use new import syntax

---

packages/react-scripts/CHANGELOG.md
packages/react-scripts/config/webpack.config.js
packages/react-scripts/config/webpack.config.ssr.js
packages/react-scripts/package.json

This is a PR to add a babel plugin (babel-plugin-istanbul) which is required by [cypress code coverage](https://docs.cypress.io/guides/tooling/code-coverage#Code-coverage-as-a-guide).
The change introduces a flag from env called `ENABLE_ISTANBUL_PLUGIN`, once the flag is presented, webpack will apply [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul) to the bundling flow. What this plugin does is it will add instrumentation to the origin code, which initially increases the bundle size. Therefore the `ENABLE_ISTANBUL_PLUGIN` is important to prevent adding the instrumentation to a prod build.

add istanbul plugin for cypress code coverage

---

.gitignore
.npmrc
packages/react-scripts/CHANGELOG.md

As OSS software we don't want to commit lock files to git, this flag
allows us to not generate them

Don't generate package-lock files

---

packages/react-scripts/package.json

Currently, Backpack React Scripts has TypeScript as a peer dependency, but only allows TypeScript 3 and 4. The latest TypeScript 5 has been released and it would be good to update to this.
This change will not force any of the existing consumers to update, but will allow those who would like to do so at their own risk. This is a very low risk change, since:
TypeScript 5 is backwards compatible.
Any changes or issues will be caught at compile time.

[ST-1798] Allow TypeScript 5 as a peer dependency.

---

.github/workflows/fork_cra5.yml

Updates the release setup to increment versions for each merge, this value will be based on the workflow run number to append to the version before publishing

[NO JIRA]: Update release CI to set new version numbers

---

packages/react-scripts/backpack-addons/ssr/customWebpackUtils.js
packages/react-scripts/config/webpack.config.js
packages/react-scripts/config/webpack.config.ssr.js

[ARGG-773]: Fix issues with TypeScript apps

---

packages/react-scripts/config/webpack.config.js
packages/react-scripts/config/webpack.config.ssr.js

[ARGG-775]: Fixed icon loading in JS and SCSS

---

packages/react-scripts/backpack-addons/cssModules.js
packages/react-scripts/backpack-addons/useTsChecker.js
packages/react-scripts/config/loaders/getAssetLoaders.js
packages/react-scripts/config/loaders/getJSLoaders.js
packages/react-scripts/config/webpack.config.js
packages/react-scripts/config/webpack.config.ssr.js

* Extracted loaders that are identical for CSR and SSR
* Removed the second round of babel-loader
* Made TS Checker optional for react-scripts build
* Made Backpack regexes optional for styles

NO_JIRA: Extract and optimise JS Loaders

---

package-lock.json
packages/react-scripts/backpack-addons/useExperimentalEsbuildLoader.js
packages/react-scripts/config/loaders/esbuildLoader.js
packages/react-scripts/config/loaders/getJSLoaders.js
packages/react-scripts/package.json

* Added esbuild-loader as an opt-in built time optimisation
* Added conversion of browserslist config to esbuild target
* Added support of keeping babel-loader for loadable components which is a hard requirement for them to work the same way as before
* I also tried to add EsbuildPlugin for minification and definitions, but it somehow showed worse results in test apps than TerserPlugin + DefinePlugin

[ARGG-864]: Experimental esbuild-loader support

---

packages/react-scripts/backpack-addons/splitChunks.js

Allow consumers configuration to turn on and off a new cacheGroup within the splitchunks addon to allow all of Bpk stylesheets to be grouped together.

[LOOM-1233]: add __unstableEnableBpkStylesChunk config option

---

package-lock.json
packages/react-scripts/package.json

Adding `@babel/plugin-proposal-private-property-in-object` as this solves the output warning that consumers get when installing BRS
```
One of your dependencies, babel-preset-react-app, is importing the
"@babel/plugin-proposal-private-property-in-object" package without
declaring it in its dependencies. This is currently working because
"@babel/plugin-proposal-private-property-in-object" is already in your
node_modules folder for unrelated reasons, but it may break at any time.
babel-preset-react-app is part of the create-react-app project, which
is not maintianed anymore. It is thus unlikely that this bug will
ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
your devDependencies to work around this error. This will make this message
go away.
```
When you install …

[NO JIRA]: Add missing babel dep to remove missing warning

---

packages/react-scripts/backpack-addons/splitChunks.js

We added Backpack Web to be in its own Backpack chunk but forgot about our bpk-logos library so it means in the case of CSS Non Determinisim these are in their own chunk and at risk of being overriding consumer styles

[ARGG-1221]: Add logos to styles group

---

packages/react-scripts/backpack-addons/splitChunks.js

PR to correct the regex for creating Backpack chunks, there was an incorrect trailing slash on the test name which meant ti could not find the packages correctly.

Update splitChunks.js regex for Backpack chunks
