Skyscanner/backpack-react-scripts

packages/react-scripts/CHANGELOG.md
packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js

[BPK-885] Fix bug with css module classes not being hashed

---

.travis.yml
packages/react-scripts/CHANGELOG.md
packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js

Fix the AMD woes webpack is causing

[BPK-1082] fix AMD issue with webpack

---

packages/react-scripts/CHANGELOG.md
packages/react-scripts/config/getLocalIdent.js
packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js
packages/react-scripts/config/webpack.config.ssr.js

Improve CSS modules hashing mechanism by adding package name as a hash prefix

[BPK-1292] - Improve CSS modules hashing mechanism

---

packages/react-scripts/CHANGELOG.md
packages/react-scripts/config/webpack.config.dev.js
packages/react-scripts/config/webpack.config.prod.js

[NOJIRA] Add polyfill opt out

---

packages/react-scripts/package.json

Fixing the annoying `ts-pnp` peer dep warning.

[BPK-1801] Fix ts-pnp peer dep warning

---

packages/react-scripts/package.json

Upgraded node-sass and fsevents so that this can work with Node 12

Bump deps for Node 12 compatibility

---

packages/react-scripts/template/src/App.scss

[NO-JIRA] Fix tokens usage

---

packages/react-scripts/README.md

Added an important message to show latest supported version

[NO JIRA]: Added supported version message

---

packages/react-error-overlay/package.json
packages/react-scripts/package.json

[NO-JIRA] Relax babel-loader dependency

---

packages/react-error-overlay/package.json
packages/react-scripts/package.json

Revert to locking babel-loader

---

packages/react-scripts/config/paths.js
packages/react-scripts/config/webpack.config.js
packages/react-scripts/config/webpack.config.ssr.js
packages/react-scripts/scripts/build.js

This is more for comment, see internal discussion in slack under backpack channel for more info.
See example here:
https://github.com/gregberge/loadable-components/blob/master/examples/server-side-rendering/webpack.config.babel.js#L50

WIP: output ssr and web chunks to different folders

---

packages/react-scripts/config/webpack.config.js
packages/react-scripts/package.json

Enable SRI

---

.travis.yml
packages/react-scripts/README.md
tasks/e2e-installs.sh
tasks/e2e-simple.sh
tasks/local-registry.sh

WIP - [BPK 3998] ci setup

---

packages/react-scripts/CHANGELOG.md
packages/react-scripts/README.md
packages/react-scripts/config/webpack.config.js
packages/react-scripts/config/webpack.config.ssr.js
packages/react-scripts/package.json
packages/react-scripts/scripts/utils/createJestConfig.js

[NO JIRA]: Adding new paths for scoped Backpack packages

---

packages/react-scripts/config/webpack.config.js
packages/react-scripts/config/webpack.config.ssr.js
packages/react-scripts/utils/getCSSModuleLocalIdentWithProjectName.js

[NO JIRA] Ident creation using Project Name

---

packages/react-scripts/backpack-addons/README.md
packages/react-scripts/backpack-addons/cssModules.js
packages/react-scripts/config/webpack.config.js
packages/react-scripts/config/webpack.config.ssr.js

[LEOP-316](https://gojira.skyscanner.net/browse/LEOP-316)
- Extracting cssModules feature to separate file
- Use `require(.../backpack-addons/...)` instead of writing it inline
- Add README.md to describe the feature

[LEOP-316]Extract cssModules feature

---

packages/react-scripts/backpack-addons/README.md

perfect README.md file
- Supplementary complete Table
- Add how-to add new feature
- Add How to upgrade from the upstream `facebook/create-react-app` repo

[LEOP-317]Prefect Backpack-addons README.md

---

packages/react-scripts/backpack-addons/runtimeChunk.js
packages/react-scripts/config/webpack.config.js
packages/react-scripts/config/webpack.config.ssr.js

runtimeChunk: Setting optimization.runtimeChunk to true adds an additional chunk containing only the runtime to each entrypoint.
step:
- extract runtimeChunk to backpack-addons
- test for banana

[LEOP-317]Extract runtimeChunk

---

.github/workflows/build-brs.yml
.github/workflows/build.yml
.github/workflows/lint.yml
tasks/e2e-installs.sh

[LEOP-294](https://gojira.skyscanner.net/browse/LEOP-294)
All workflows are running with Node.js 14.x but all will be running with Node.js 16 since it will be Node.js 16 at Skyscanner too.
- Upgrade node version to 16.x in the `workflows` folder
- Update the tests in the `e2e-installs.sh`
- Update the Backpack [cra-template-backpack](https://github.com/Skyscanner/cra-template-backpack) dependences

[LEOP-294] Update node to 16.x in workflow

---

.github/workflows/fork_cra5.yml

This PR simplifies the release process to be even easier and less complicated.
It also switches from using a script that doesn't live in this branch anymore which I noticed I was using possibly based on old or incorrect scripts.

[ARGG-784]: Release pipeline for cra5 testing

---

.github/workflows/main.yml

Updates CI to make dev releases when merged to main for testing
Updates CI to make stable version published when release created

[NO JIRA]: Update CI for dev and stable releases

---

.github/workflows/main.yml

Improves some wording to the name to avoid confusion in the actions view
Fixes an issue where when merged to main the dev publish was not triggering

[NO JIRA]: Improve releases process further

---

package-lock.json
packages/react-scripts/package.json

[NO JIRA]: Upgrade sass-loader to latest
